SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_TOPIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_TOPIC` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_TOPIC` (
  `TOPIC_ID` INT NOT NULL ,
  `TOPIC_NAME` VARCHAR(300) NULL ,
  PRIMARY KEY (`TOPIC_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_TOPIC_LINK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_TOPIC_LINK` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_TOPIC_LINK` (
  `LINKED_TOPIC_ID` INT NOT NULL ,
  `PARENT_TOPIC_ID` INT NOT NULL ,
  PRIMARY KEY (`LINKED_TOPIC_ID`, `PARENT_TOPIC_ID`) ,
  INDEX `fk_UNIDO_TOPIC_has_UNIDO_TOPIC_UNIDO_TOPIC1` (`PARENT_TOPIC_ID` ASC) ,
  INDEX `fk_UNIDO_TOPIC_has_UNIDO_TOPIC_UNIDO_TOPIC` (`LINKED_TOPIC_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_TOPIC_has_UNIDO_TOPIC_UNIDO_TOPIC`
    FOREIGN KEY (`LINKED_TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_TOPIC_has_UNIDO_TOPIC_UNIDO_TOPIC1`
    FOREIGN KEY (`PARENT_TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_TEMPLATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE` (
  `ENTITY_TEMPLATE_ID` INT NOT NULL ,
  `TEMPLATE_NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ENTITY_TEMPLATE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY` (
  `ENTITY_ID` INT NOT NULL ,
  `ENTITY_TEMPLATE_ID` INT NOT NULL ,
  `ENTITY_NAME` VARCHAR(300) NULL ,
  PRIMARY KEY (`ENTITY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_UNIDO_ENTITY_TEMPLATE1` (`ENTITY_TEMPLATE_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_UNIDO_ENTITY_TEMPLATE1`
    FOREIGN KEY (`ENTITY_TEMPLATE_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE` (`ENTITY_TEMPLATE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` (
  `TEMPLATE_PROPERTY_ID` INT NOT NULL ,
  `ENTITY_TEMPLATE_ID` INT NOT NULL ,
  `PROPERTY_NAME` VARCHAR(100) NULL ,
  `DISPLAY_IN_GRID` TINYINT(1) NULL ,
  PRIMARY KEY (`TEMPLATE_PROPERTY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_UNIDO_ENTITY_TEMPLATE1` (`ENTITY_TEMPLATE_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_UNIDO_ENTITY_TEMPLATE1`
    FOREIGN KEY (`ENTITY_TEMPLATE_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE` (`ENTITY_TEMPLATE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_PROPERTY` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_PROPERTY` (
  `ENTITY_PROPERTY_ID` INT NOT NULL ,
  `ENTITY_ID` INT NOT NULL ,
  `TEMPLATE_PROPERTY_ID` INT NOT NULL ,
  PRIMARY KEY (`ENTITY_PROPERTY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_PARAMETER_UNIDO_ENTITY1` (`ENTITY_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_PROPERTY_UNIDO_ENTITY_TEMPLATE_PROPERTY1` (`TEMPLATE_PROPERTY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_PARAMETER_UNIDO_ENTITY1`
    FOREIGN KEY (`ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_PROPERTY_UNIDO_ENTITY_TEMPLATE_PROPERTY1`
    FOREIGN KEY (`TEMPLATE_PROPERTY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` (`TEMPLATE_PROPERTY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_REFERENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_REFERENCE` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_REFERENCE` (
  `ENTITY_ID` INT NOT NULL ,
  `TOPIC_ID` INT NOT NULL ,
  PRIMARY KEY (`ENTITY_ID`, `TOPIC_ID`) ,
  INDEX `fk_UNIDO_ENTITY_has_UNIDO_TOPIC_UNIDO_TOPIC1` (`TOPIC_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_has_UNIDO_TOPIC_UNIDO_ENTITY1` (`ENTITY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_has_UNIDO_TOPIC_UNIDO_ENTITY1`
    FOREIGN KEY (`ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_has_UNIDO_TOPIC_UNIDO_TOPIC1`
    FOREIGN KEY (`TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_LINK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_LINK` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_LINK` (
  `LINKED_ENTITY_ID` INT NOT NULL ,
  `PARENT_ENTITY_ID` INT NOT NULL ,
  PRIMARY KEY (`LINKED_ENTITY_ID`, `PARENT_ENTITY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_has_UNIDO_ENTITY_UNIDO_ENTITY2` (`PARENT_ENTITY_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_has_UNIDO_ENTITY_UNIDO_ENTITY1` (`LINKED_ENTITY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_has_UNIDO_ENTITY_UNIDO_ENTITY1`
    FOREIGN KEY (`LINKED_ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_has_UNIDO_ENTITY_UNIDO_ENTITY2`
    FOREIGN KEY (`PARENT_ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_VALUE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_VALUE_TYPE` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_VALUE_TYPE` (
  `VALUE_TYPE_ID` INT NOT NULL ,
  `FORMAT` VARCHAR(45) NULL ,
  `TYPE` VARCHAR(45) NULL ,
  `UNIT_OF_MEASURE` VARCHAR(15) NULL ,
  PRIMARY KEY (`VALUE_TYPE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_PROPERTY_VALUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_PROPERTY_VALUE` ;

CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_PROPERTY_VALUE` (
  `PROPERTY_VALUE_ID` INT NOT NULL ,
  `ENTITY_PROPERTY_ID` INT NOT NULL ,
  `VALUE_TYPE_ID` INT NOT NULL ,
  `VALUE` BLOB NULL ,
  PRIMARY KEY (`PROPERTY_VALUE_ID`) ,
  INDEX `fk_UNIDO_PROPERTY_VALUE_UNIDO_ENTITY_PROPERTY1` (`ENTITY_PROPERTY_ID` ASC) ,
  INDEX `fk_UNIDO_PROPERTY_VALUE_UNIDO_VALUE_TYPE1` (`VALUE_TYPE_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_PROPERTY_VALUE_UNIDO_ENTITY_PROPERTY1`
    FOREIGN KEY (`ENTITY_PROPERTY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_PROPERTY` (`ENTITY_PROPERTY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_PROPERTY_VALUE_UNIDO_VALUE_TYPE1`
    FOREIGN KEY (`VALUE_TYPE_ID` )
    REFERENCES `eetdb`.`UNIDO_VALUE_TYPE` (`VALUE_TYPE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
