SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

-- -----------------------------------------------------
-- Drop tables `eetdb`.*
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`UNIDO_TOPIC_LINK` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_LINK` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_REFERENCE` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_TOPIC` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_PROPERTY` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_VALUE_TYPE` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE` ;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_BLOB`;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_TOPIC_SEARCH`;
DROP TABLE IF EXISTS `eetdb`.`UNIDO_ENTITY_SEARCH`;
-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_TOPIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_TOPIC` (
  `TOPIC_ID`          INT           NOT NULL AUTO_INCREMENT,
  `TOPIC_NAME`        NVARCHAR(100) NOT NULL ,
  `DESCRIPTION`       NVARCHAR(300)     NULL ,
  `VERSION`           INT           NOT NULL DEFAULT '0',
  `UPDATED_BY`        NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`       TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`TOPIC_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_TOPIC_LINK`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_TOPIC_LINK` (  
  `LINKED_TOPIC_ID` INT NOT NULL ,
  `PARENT_TOPIC_ID` INT NOT NULL ,
  PRIMARY KEY (`LINKED_TOPIC_ID`, `PARENT_TOPIC_ID`) ,
  INDEX `fk_UNIDO_TOPIC_PARENT_TOPIC_ID` (`PARENT_TOPIC_ID` ASC) ,
  INDEX `fk_UNIDO_TOPIC_LINKED_TOPIC_ID` (`LINKED_TOPIC_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_TOPIC_LINKED_TOPIC_ID`
    FOREIGN KEY (`LINKED_TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_TOPIC_PARENT_TOPIC_ID`
    FOREIGN KEY (`PARENT_TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_VALUE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_VALUE_TYPE` (
  `VALUE_TYPE_ID`   INT           NOT NULL AUTO_INCREMENT,
  `FORMAT`          NVARCHAR(45)  NULL ,
  `TYPE`            NVARCHAR(45)  NULL ,
  `VERSION`         INT           NOT NULL DEFAULT '0',
  `UPDATED_BY`      NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`     TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`VALUE_TYPE_ID`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_TEMPLATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE` (
  `ENTITY_TEMPLATE_ID` INT           NOT NULL AUTO_INCREMENT,
  `TEMPLATE_CODE`      NVARCHAR(30)  NOT NULL ,
  `TEMPLATE_NAME`      NVARCHAR(45)  NOT NULL ,
  `VERSION`            INT           NOT NULL DEFAULT '0',
  `UPDATED_BY`         NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`        TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`ENTITY_TEMPLATE_ID`),
  UNIQUE INDEX `uk_UNIDO_ENTITY_TEMPLATE_CODE` (`TEMPLATE_CODE` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` (
  `TEMPLATE_PROPERTY_ID` INT           NOT NULL AUTO_INCREMENT,
  `ENTITY_TEMPLATE_ID`   INT           NOT NULL ,
  `PROPERTY_CODE`        NVARCHAR(30)  NOT NULL ,
  `PROPERTY_NAME`        NVARCHAR(100) NOT NULL ,
  `VERSION`              INT           NOT NULL DEFAULT '0',
  `VALUE_TYPE_ID`        INT           NOT NULL ,
  `UNIT_OF_MEASURE`      NVARCHAR(30)      NULL ,
  `DISPLAY_IN_GRID`      TINYINT(1)    NOT NULL DEFAULT '0',
  `SEARCHABLE`           TINYINT(1)    NOT NULL DEFAULT '0',
  `MANDATORY`            TINYINT(1)    NOT NULL DEFAULT '0',
  `UPDATED_BY`           NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`          TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`TEMPLATE_PROPERTY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_ENTITY_TEMPLATE_ID` (`ENTITY_TEMPLATE_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_VALUE_TYPE_ID` (`VALUE_TYPE_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_ENTITY_TEMPLATE_ID`
    FOREIGN KEY (`ENTITY_TEMPLATE_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE` (`ENTITY_TEMPLATE_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_TEMPLATE_PROPERTY_VALUE_TYPE_ID`
    FOREIGN KEY (`VALUE_TYPE_ID` )
    REFERENCES `eetdb`.`UNIDO_VALUE_TYPE` (`VALUE_TYPE_ID` )
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  UNIQUE INDEX `uk_UNIDO_ENTITY_TEMPLATE_PROPERTY_CODE` (`ENTITY_TEMPLATE_ID`, `PROPERTY_CODE` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_BLOB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_BLOB` (
  `BLOB_ID`   	       INT           NOT NULL AUTO_INCREMENT,
  `DATA_TYPE`          VARCHAR(100)  NOT NULL ,
  `FILE_NAME`          VARCHAR(100)      NULL ,
  `CONTENT`		       MEDIUMBLOB    NOT NULL ,
  `VERSION`            INT           NOT NULL DEFAULT '0',
  `UPDATED_BY`         NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`        TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`BLOB_ID`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY` (
  `ENTITY_ID`          INT            NOT NULL ,
  `ENTITY_TEMPLATE_ID` INT            NOT NULL ,
  `ENTITY_NAME`        NVARCHAR(255)  NOT NULL ,
  `VERSION`            INT            NOT NULL DEFAULT '0',
  `STATUS`             NVARCHAR(30)   NOT NULL DEFAULT 'PENDING',
  `UPDATED_BY`         NVARCHAR(100)  NOT NULL ,
  `UPDATE_DATE`        TIMESTAMP      NOT NULL ,
  PRIMARY KEY (`ENTITY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_ENTITY_TEMPLATE_ID` (`ENTITY_TEMPLATE_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_ENTITY_TEMPLATE_ID`
    FOREIGN KEY (`ENTITY_TEMPLATE_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE` (`ENTITY_TEMPLATE_ID` )
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  UNIQUE INDEX `uk_UNIDO_ENTITY_NAME` (`ENTITY_TEMPLATE_ID`, `ENTITY_NAME` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_PROPERTY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_PROPERTY` (
  `ENTITY_PROPERTY_ID`   INT           NOT NULL AUTO_INCREMENT,
  `ENTITY_ID`            INT           NOT NULL ,
  `TEMPLATE_PROPERTY_ID` INT           NOT NULL ,
  `VALUE`                NVARCHAR(512) NOT NULL ,
  `VERSION`              INT           NOT NULL DEFAULT '0',
  `UPDATED_BY`           NVARCHAR(100) NOT NULL ,
  `UPDATE_DATE`          TIMESTAMP     NOT NULL ,
  PRIMARY KEY (`ENTITY_PROPERTY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_PROPERTY_ENTITY_ID` (`ENTITY_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_PROPERTY_TEMPLATE_PROPERTY_ID` (`TEMPLATE_PROPERTY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_PROPERTY_ENTITY_ID`
    FOREIGN KEY (`ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_PROPERTY_TEMPLATE_PROPERTY_ID`
    FOREIGN KEY (`TEMPLATE_PROPERTY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY_TEMPLATE_PROPERTY` (`TEMPLATE_PROPERTY_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_REFERENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_REFERENCE` (
  `ENTITY_ID` INT NOT NULL ,
  `TOPIC_ID`  INT NOT NULL ,
  PRIMARY KEY (`ENTITY_ID`, `TOPIC_ID`) ,
  INDEX `fk_UNIDO_ENTITY_TOPIC_ID` (`TOPIC_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_ENTITY_ID` (`ENTITY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_ENTITY_ID`
    FOREIGN KEY (`ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_TOPIC_ID`
    FOREIGN KEY (`TOPIC_ID` )
    REFERENCES `eetdb`.`UNIDO_TOPIC` (`TOPIC_ID` )
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_LINK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_LINK` (
  `LINKED_ENTITY_ID` INT NOT NULL ,
  `PARENT_ENTITY_ID` INT NOT NULL ,
  PRIMARY KEY (`LINKED_ENTITY_ID`, `PARENT_ENTITY_ID`) ,
  INDEX `fk_UNIDO_ENTITY_PARENT_ENTITY_ID` (`PARENT_ENTITY_ID` ASC) ,
  INDEX `fk_UNIDO_ENTITY_LINKED_ENTITY_ID` (`LINKED_ENTITY_ID` ASC) ,
  CONSTRAINT `fk_UNIDO_ENTITY_LINKED_ENTITY_ID`
    FOREIGN KEY (`LINKED_ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDO_ENTITY_PARENT_ENTITY_ID`
    FOREIGN KEY (`PARENT_ENTITY_ID` )
    REFERENCES `eetdb`.`UNIDO_ENTITY` (`ENTITY_ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_TOPIC_SEARCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_TOPIC_SEARCH` (
  `TOPIC_ID`          INT           NOT NULL ,
  `TOPIC_NAME`        NVARCHAR(100) NOT NULL ,
  `DESCRIPTION`       NVARCHAR(300)     NULL ,
  PRIMARY KEY (`TOPIC_ID`),
  FULLTEXT KEY `idx_ft_topic_name_desc` (`TOPIC_NAME`,`DESCRIPTION`))
ENGINE = MYISAM;

-- -----------------------------------------------------
-- Table `eetdb`.`UNIDO_ENTITY_SEARCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eetdb`.`UNIDO_ENTITY_SEARCH` (
  `ENTITY_ID`         INT           NOT NULL ,
  `ENTITY_NAME`       NVARCHAR(300) NOT NULL ,
  `DESCRIPTION`       NVARCHAR(512)     NULL ,
  `VENDOR_CODE`       NVARCHAR(512)     NULL ,
  PRIMARY KEY (`ENTITY_ID`),
  FULLTEXT KEY `idx_ft_entity_name_desc` (`ENTITY_NAME`,`DESCRIPTION`),
  FULLTEXT KEY `idx_ft_entity_code` (`VENDOR_CODE`))
ENGINE = MYISAM;

-- -----------------------------------------------------
-- Table `eetdb`.`SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eetdb`.`SEQUENCE`;
CREATE TABLE `eetdb`.`SEQUENCE` (id INT NOT NULL); 
INSERT INTO `eetdb`.`SEQUENCE` VALUES (1000); 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;