DELIMITER //

DROP PROCEDURE `SEARCH_TOPIC`
//

DROP PROCEDURE `SEARCH`
//

CREATE PROCEDURE SEARCH_TOPIC(P_TEXT varchar(200))
BEGIN
	declare v_text VARCHAR(200);
	set v_text = format_search_string(p_text);

	SELECT *
		 , MATCH (TOPIC_NAME, DESCRIPTION) AGAINST (v_text IN BOOLEAN MODE) as REL
	FROM `UNIDO_TOPIC_SEARCH`
	WHERE MATCH (TOPIC_NAME, DESCRIPTION) AGAINST (v_text IN BOOLEAN MODE) > 0
	ORDER BY REL DESC;
END//

CREATE PROCEDURE SEARCH(P_TEXT varchar(200))
BEGIN
	declare v_text VARCHAR(200);
	set v_text = format_search_string(p_text);

	SELECT *
		 , MATCH (ENTITY_NAME, DESCRIPTION) AGAINST (v_text IN BOOLEAN MODE) as REL
		 , MATCH (`VENDOR_CODE`) AGAINST (v_text IN BOOLEAN MODE) REL_CODE
	  FROM `UNIDO_ENTITY_SEARCH`
	 WHERE MATCH (ENTITY_NAME, DESCRIPTION) AGAINST (v_text IN BOOLEAN MODE) > 0
        OR MATCH (`VENDOR_CODE`) AGAINST (v_text IN BOOLEAN MODE) > 0
	 ORDER BY REL DESC;
END//

GRANT execute ON PROCEDURE `SEARCH_TOPIC` TO eetSite
//

GRANT execute ON PROCEDURE `SEARCH` TO eetSite
//

