delimiter //
DROP TRIGGER IF EXISTS add_topic_search
//
DROP TRIGGER IF EXISTS update_topic_search
//
DROP TRIGGER IF EXISTS delete_topic_search
//

CREATE TRIGGER add_topic_search AFTER INSERT ON UNIDO_TOPIC
  FOR EACH ROW 
  BEGIN
    INSERT INTO UNIDO_TOPIC_SEARCH 
	   SET TOPIC_ID = NEW.TOPIC_ID
         , TOPIC_NAME = NEW.TOPIC_NAME
         , DESCRIPTION = NEW.DESCRIPTION;
  END
//

CREATE TRIGGER update_topic_search BEFORE UPDATE ON UNIDO_TOPIC
  FOR EACH ROW 
  BEGIN
    UPDATE UNIDO_TOPIC_SEARCH 
	   SET TOPIC_NAME = NEW.TOPIC_NAME
         , DESCRIPTION = NEW.DESCRIPTION
     WHERE TOPIC_ID = OLD.TOPIC_ID;
  END;
//

CREATE TRIGGER delete_topic_search BEFORE DELETE ON UNIDO_TOPIC
  FOR EACH ROW 
  BEGIN
    DELETE
	  FROM UNIDO_TOPIC_SEARCH 
     WHERE TOPIC_ID = OLD.TOPIC_ID;
  END;
//

delimiter //
DROP TRIGGER IF EXISTS add_entity_search
//
DROP TRIGGER IF EXISTS update_entity_search
//
DROP TRIGGER IF EXISTS delete_entity_search
//

CREATE TRIGGER add_entity_search AFTER INSERT ON UNIDO_ENTITY
  FOR EACH ROW 
  BEGIN
    INSERT INTO UNIDO_ENTITY_SEARCH 
	   SET ENTITY_ID = NEW.ENTITY_ID
         , ENTITY_NAME = NEW.ENTITY_NAME;
  END
//

CREATE TRIGGER update_entity_search BEFORE UPDATE ON UNIDO_ENTITY
  FOR EACH ROW 
  BEGIN
    UPDATE UNIDO_ENTITY_SEARCH 
	   SET ENTITY_NAME = NEW.ENTITY_NAME
     WHERE ENTITY_ID = OLD.ENTITY_ID;
  END;
//

CREATE TRIGGER delete_entity_search BEFORE DELETE ON UNIDO_ENTITY
  FOR EACH ROW 
  BEGIN
    DELETE
	  FROM UNIDO_ENTITY_SEARCH 
     WHERE ENTITY_ID = OLD.ENTITY_ID;
  END;
//

DROP TRIGGER IF EXISTS add_entity_property_search
//
DROP TRIGGER IF EXISTS update_entity_property_search
//
DROP TRIGGER IF EXISTS delete_entity_property_search
//

CREATE TRIGGER add_entity_property_search AFTER INSERT ON UNIDO_ENTITY_PROPERTY
  FOR EACH ROW 
  BEGIN
    UPDATE UNIDO_ENTITY_SEARCH 
	   SET DESCRIPTION = NEW.`VALUE`
	 WHERE ENTITY_ID = NEW.ENTITY_ID
	   AND NEW.TEMPLATE_PROPERTY_ID IN (SELECT TEMPLATE_PROPERTY_ID
										  FROM UNIDO_ENTITY_TEMPLATE_PROPERTY
										 WHERE PROPERTY_CODE = 'DESCRIPTION');
  END
//

CREATE TRIGGER update_entity_property_search BEFORE UPDATE ON UNIDO_ENTITY_PROPERTY
  FOR EACH ROW 
  BEGIN
    UPDATE UNIDO_ENTITY_SEARCH 
	   SET DESCRIPTION = NEW.`VALUE`
     WHERE ENTITY_ID = OLD.ENTITY_ID
	   AND OLD.TEMPLATE_PROPERTY_ID IN (SELECT TEMPLATE_PROPERTY_ID
										  FROM UNIDO_ENTITY_TEMPLATE_PROPERTY
										 WHERE PROPERTY_CODE = 'DESCRIPTION');
  END
//

CREATE TRIGGER delete_entity_property_search BEFORE DELETE ON UNIDO_ENTITY_PROPERTY
  FOR EACH ROW 
  BEGIN
    UPDATE UNIDO_ENTITY_SEARCH 
	   SET DESCRIPTION = NULL
     WHERE ENTITY_ID = OLD.ENTITY_ID
	   AND OLD.TEMPLATE_PROPERTY_ID IN (SELECT TEMPLATE_PROPERTY_ID
										  FROM UNIDO_ENTITY_TEMPLATE_PROPERTY
										 WHERE PROPERTY_CODE = 'DESCRIPTION');
  END
//