set @last_id = eetdb.add_entity('VENDOR', '');
call add_entity_property(@last_id, 'PICTURE', '', null, null, null);
call add_entity_property(@last_id, 'URL', '', null, null, null);
call add_entity_property(@last_id, 'DESCRIPTION', '', null, null, null);
call add_entity_property(@last_id, 'DETAILS', null, '', 'TEXT', null);
call add_entity_property(@last_id, 'ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'PHONE', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_URL', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_PHONE', '', null, null, null);

set @last_id = eetdb.add_entity('VENDOR', '');
call add_entity_property(@last_id, 'PICTURE', '', null, null, null);
call add_entity_property(@last_id, 'URL', '', null, null, null);
call add_entity_property(@last_id, 'DESCRIPTION', '', null, null, null);
call add_entity_property(@last_id, 'DETAILS', null, '', 'TEXT', null);
call add_entity_property(@last_id, 'ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'PHONE', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_URL', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_PHONE', '', null, null, null);

set @last_id = eetdb.add_entity('VENDOR', '');
call add_entity_property(@last_id, 'PICTURE', '', null, null, null);
call add_entity_property(@last_id, 'URL', '', null, null, null);
call add_entity_property(@last_id, 'DESCRIPTION', '', null, null, null);
call add_entity_property(@last_id, 'DETAILS', null, '', 'TEXT', null);
call add_entity_property(@last_id, 'ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'PHONE', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_URL', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_PHONE', '', null, null, null);

set @last_id = eetdb.add_entity('VENDOR', '');
call add_entity_property(@last_id, 'PICTURE', '', null, null, null);
call add_entity_property(@last_id, 'URL', '', null, null, null);
call add_entity_property(@last_id, 'DESCRIPTION', '', null, null, null);
call add_entity_property(@last_id, 'DETAILS', null, '', 'TEXT', null);
call add_entity_property(@last_id, 'ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'PHONE', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_URL', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_PHONE', '', null, null, null);

set @last_id = eetdb.add_entity('VENDOR', '');
call add_entity_property(@last_id, 'PICTURE', '', null, null, null);
call add_entity_property(@last_id, 'URL', '', null, null, null);
call add_entity_property(@last_id, 'DESCRIPTION', '', null, null, null);
call add_entity_property(@last_id, 'DETAILS', null, '', 'TEXT', null);
call add_entity_property(@last_id, 'ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'PHONE', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_URL', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_ADDRESS', '', null, null, null);
call add_entity_property(@last_id, 'DISTRIBUTOR_PHONE', '', null, null, null);
